### ISSUE TITLE
If the parse_ini_file() method is in the disabled_function list in php.ini

### ISSUE THREAD

**Issue by sevkialacatli** [apimatic/jsonmapper#47]
**Describe the bug**
'I am getting an error in the line "parse_ini_file($iniPath);" in the JsonMapper.php file. In php.ini, this method "parse_ini_file" is in the "disable_functions" list. 
Error message: "Fatal error: Uncaught Error: Call to undefined function apimatic\jsonmapper\parse_ini_file()". 

**Expected behavior**
if it is not in the disabled function here, can you add the control?

**Screenshots**
<img width="1280" alt="resim" src="https://github.com/apimatic/jsonmapper/assets/1853829/33d482a5-9265-449b-b17a-4a73a55e45ae">

**Comment by asadali214** [comment]
@sevkialacatli The PR: https://github.com/apimatic/jsonmapper/pull/48 will close this issue

**Comment by sevkialacatli** [comment]
Thanks for the quick fix @asadali214

**Comment by asadali214** [comment]
@sevkialacatli Welcome!
This fix is also released in version [v3.1.3](https://github.com/apimatic/jsonmapper/releases/tag/3.1.3)

**Comment by sevkialacatli** [comment]
Hi @asadali214 
in the apimatic/core package it is called 3.1.1 will it be updated there ?

![resim](https://github.com/apimatic/jsonmapper/assets/1853829/d9784dc7-7113-4ab7-a040-b3a4027ab8d4)

**Comment by asadali214** [comment]
Hey, @sevkialacatli the apimatic/jsonmapper dependency version in apimatic/core is `^3.1.1`.

Here the caret (^) symbol indicates a compatible version range. It means that versions up to, but excluding, the next major release are allowed.

So, the version `^3.1.1`, allows any version from `3.1.1` up to, but excluding, `4.0.0`. We have used it to ensure compatibility with new features and bug fixes but not breaking changes.

You might need to run the command `composer update` to update your dependencies
