### ISSUE TITLE
Php 8 support

### ISSUE THREAD

**Issue by aios** [apimatic/jsonmapper#5]
subj.

**Comment by thehappybug** [comment]
PHP 8 fixes were added recently. Please migrate to the latest version, 2.0.2.

**Comment by Druget** [comment]
@aios Aios Габриелян Давид Меликович - мошенник! Кинул на $840 долларов, не выполнил работу и пропал.
Номер карты приватбанк 5218572221792372 
5218 5722 2179 2372
gabrielyan david - conman! Cheated me out of $$$ 840, didn't do the job, and disappeared.
